apiVersion: harness.io/v1
kind: Component
type: service
identifier: harnessguestbooktest
name: harness_guestbook_test
owner: Unknown
spec:
  lifecycle: Unknown
  sourceCode:
    provider: Github
    repoName: harness-entities
    connectorRef: account.Freshgithubconnector
    branch: main
    monoRepo: false
    url: https://github.com/mehar221/harness-entities/tree/main
